// Aditya Singh Gajawat All Rights Reserved

#pragma once
#include "NativeGameplayTags.h" 

namespace WarriorGameplayTags
{
	/** INPUT TAGS **/
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipKatana);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipKatana);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Light_Katana);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Heavy_Katana);

	/** PLAYER TAGS **/
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Katana);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Effect_Attack_Light);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Effect_Attack_Heavy);

	/*ABILITY TAGS (MAINLY USED FOR BLOCKING OTHER ABILITY WHILE DOING ONE)*/
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_OnEquip_Katana);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_OnUnequip_Katana);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Katana);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Katana);

	/** GAMEPLAY EVENTS **/
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipKatana);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnequipKatana);
	/**SHARED GAMEPLAY EVENTS**/
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_RegisterHit);
	GAS_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_EffectSpec_BaseDamage);
}